### ISSUE TITLE
Add category data type to describe 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#113] opened 2020-03-25 03:53 UTC
In describe menu for categorical data type it can show
*  value_counts()
* most frequent variables 
* all unique values if there are less than 100
* distribution histogram chart

**Comment by aschonfeld** [comment] 2020-03-25 11:39
@reza
* The "Value Counts" chart in the "Column Analysis" popup currently works for category data
![image](https://user-images.githubusercontent.com/11547371/77532453-449e4300-6e6b-11ea-85f8-3bf873e2dc73.png)

* I believe this chart should handle your 2nd request as well

* Currently the default behavior for the unique values display in the "Describe" popup works exactly as requested (show top 100 values based on value count if there is greater than 100 otherwise show everything)  Are you requesting that the "Value Counts" chart be filtered down to the top 100 most frequent values?  Certainly seems like a good idea.

![image](https://user-images.githubusercontent.com/11547371/77532252-df4a5200-6e6a-11ea-8342-82bd45665bc6.png)


* still not sure what you mean by "distribution histogram chart"?  I don't think its possible to show a histogram of categorical values.

**Comment by reza1615** [comment] 2020-03-25 12:39
it is possible for ordinal categorical variables 
https://mathalope.co.uk/2015/03/19/descriptive-statistics-can-we-plot-histogram-for-categorical-variables/

**Comment by reza1615** [comment] 2020-03-25 12:42
《Are you requesting that the "Value Counts" chart be filtered down to the top 100 most frequent values?》
yes. it can be set by user like top 50 or top 120 and by default it can be 100

**Comment by reza1615** [comment] 2020-03-25 12:46
also please add it to readme

**Comment by aschonfeld** [comment] 2020-03-25 12:49
Ok, so the difference between what they are showing their chart and what we show for the "Value Counts" chart I showed you earlier is that they are sorting their categories by something (in their example "warmth").

Unless there is some standard metric for sorting categories other than their natural sort (strings -> alphabetical, numbers -> increasing order) there's not much I can do.

There might be some way if we offered the users the option to select another column and then maybe an aggregation and we sort the column based on the values returned by grouping the other column on the category and applying the aggregation, but I feel like that might be adding extra functionality that will be rarely used.  Maybe I'm wrong.

I do think the ability to control the amount of columns that come back is a great idea.  Similar to the "bins" input I have for the histogram chart.

**Comment by aschonfeld** [comment] 2020-03-25 17:30
@reza1615 Here's a [demo](https://youtu.be/CIJmY7OYfic)of what I have for the ordinal selection functionality & limiting how many values come back.  Just for some context I clicked a categorical column (category) and then I choosing ordinals based on some float columns (Col0 -> Col9) and toggling the aggregation that gets used.

Please let me know if this works for you and I'll move forward with the changes.  Thanks

**Comment by reza1615** [comment] 2020-03-26 03:20
That is great thanks. is it possible also to add these features to the description window?

**Comment by aschonfeld** [comment] 2020-03-28 23:42
@reza1615 I'm going to close this for now since I've added most of this to v1.8.1 and if you want to open a new issue to move "Column Analysis" into the "Describe" popup as well that works :)

**Closed by aschonfeld** 2020-03-28 23:42 UTC

**Comment by reza1615** [comment] 2020-03-29 01:03
It doesnt work when only I change the top number without changing ordinals.

**Comment by aschonfeld** [comment] 2020-03-29 01:26
So you mean it doesn’t accept updates to “Top” without a change to the ordinal column?

**Comment by reza1615** [comment] 2020-03-29 01:27
yes

**Comment by aschonfeld** [comment] 2020-03-29 01:29
Got it, will take a look in the morning

**Comment by aschonfeld** [comment] 2020-03-29 02:40
@reza1615 i cant seem to reproduce the issue.  Can you let me know what column your viewing and any other operations you’re doing to reproduce the issue?

**Comment by reza1615** [comment] 2020-03-29 03:28
I found the problem. Please get Exterior_color column analysis. It shows the top =100 which should be max (number of categories) for here it is 12. 
I checked it with a cellphone after changing number to 20 it doesn't change :)

**Comment by aschonfeld** [comment] 2020-03-29 13:29
Ok, I've updated the code so that on initial load of "Value Counts" & "Category" it will also return what top should be (either the maximum amount of values are or 100 if there is more than 100).

Users can still type in any value they want in the input box, but there's not much I can do about that.
