### ISSUE TITLE
Dtale v.1.8.0 is extremely slower than previous versions in data load 

### ISSUE THREAD

**Issue by MichalRIcar** [man-group/dtale#109] opened 2020-03-24 17:00 UTC
Please verify that new version behaves reasonably even with larger data sets as I work with >200K obs and new Dtale loading data over 1min (!) compared to 7s  which is the performance of v1.7

**Comment by aschonfeld** [comment] 2020-03-24 18:36
@MichalRIcar I've started doing some benchmark testing around the initial startup and I'm getting similar start times between v1.7.0 & v1.8.0 for a dataframe with 2 million rows and 100 columns.  The time i'm seeing is about 6.9 seconds in python 27-3 for both and 6.7 seconds for both in python 36-1.

Also no difference in timings between python 27-3 or 36-1.

Is there any chance you could send me some information around the shape of your data and the data types of the columns involved?

**Comment by MichalRIcar** [comment] 2020-03-24 18:54
Hello Adrew, you are right, I tried to switch to older versions (1.7.x) and all of it behaves same. 

I assume it is dependency on underlying library. Just cross-checked with qgrid and very same data has time load >2s, pandas view >1s. 

As I observe this heavy processing for last few days, I am trying to remember what were the last updates of packages that I did recently. 

Perhaps updates of plotly, orca, numpy. 

Thank you very much for such a prompt response, truly amazing!

Michal

**Comment by aschonfeld** [comment] 2020-03-24 19:06
@MichalRIcar no problem at all.  Always happy to help. :)

So is there still an issue or was it just a problem around the fact that it had to install the new packages?  None of the plotly stuff should come into play until you start using the "Charts" popup so that shouldn't be an issue at startup.

**Comment by MichalRIcar** [comment] 2020-03-24 19:09
The issue remains, D-Tale has load 1min vs. qgrid  2s vs. pandas view  less than 1s. 

I am trying to update all packages and let you know.

**Comment by aschonfeld** [comment] 2020-03-24 20:13
@MichalRIcar any chance you could send the output of calling `.dtypes` on your dataframe?  If that information is sensitive I understand.  Just trying to get a sense for what the data types are so I can try to mimic.

There's also a chance that the time is being spent just starting up the flask process which would be independent of data size.  This could definitely be a difference between dtale vs. qgrid & pandas view because neither of those startup a separate process but uses the components that jupyter gives you directly.

Still not sure why it would be so slow to start that though since when I use it on my jupyter notebook its take me a few seconds for sure, here's a clip of me loading a dataframe w/ [200K rows/100 cols](https://www.youtube.com/watch?v=dFhQJ1vcma4&feature=youtu.be) but not a minute.

So if you're trying trying to get the same startup speed qgrid or pandas view we may never get there but I'd hope there might be a lot more functionality available for that to be overlooked :crossed_fingers:

**Comment by MichalRIcar** [comment] 2020-03-25 05:52
Hello,

 

After the update of all packages it is still same issue:



 



 

I tried to restrict data to 100obs and 30 columns and it behaves just same, so definitely it is called process not the data structure.

 

As ex-SAS guy I really love D-Tale, so much appreciate your support!

 

 

Thanks,

Michal

**Comment by aschonfeld** [comment] 2020-03-25 10:54
@MichalRIcar thanks again for all your patience with this.  There's one last thing I can suggest.  If running within a jupyter notebook try using this snippet:

```
import dtale

d = dtale.show(df)
print(d._main_url)
```

So rather then jumping directly to displaying an IFrame this will render a link to the main url of your D-Tale process.  So this should ignore any of the other logic I have around checking whether the Flask process is up and running before rendering the IFrame. 

You should be able to click the URL and it will bring you to your grid on a separate tab.  Maybe not the best functionality but I'm hoping this will at least show us the cause of your slowness on startup. 🤞

**Comment by MichalRIcar** [comment] 2020-03-25 11:21
That is pretty interesting behavior, now it split the time by 2 almost exactly, first part:



 

And another 30sec to open the link. So original 1 min is distributed.

 

Still can’t wait to find out what is truly happening…

**Comment by aschonfeld** [comment] 2020-03-25 12:41
Ok, next question.  After you've called `dtale.show(df)` the first time does calling it a second time in another cell using `dtale.show(df, ignore_duplicate=True)` take the same amount of time?

I would think not because the Flask process has already been started at that point and its merely adding more data to the global state to be viewable in D-Tale.  If it does still take a long time then I'm wondering if there is something going on with your firewall that is slowing the initial connections to the app.

**Comment by MichalRIcar** [comment] 2020-03-26 15:23
Hello,

 

I decided to do it from the scratch to check possible hidden incompatibilities with another packages. I uninstalled anaconda and cleaned all the stuff and after fresh installation the time load is 16s instead of 57s, thus definitely it was something with other packages.

 

However, still it’s double than before when the load time was 8s. (exactly same data)

 

I also find out that if I open several session of d-tale in one Jupyter then the whole work in the Jupyter becomes extra slower and heavier even though I have 32GB, Intel 9thG. So wondering why is that?

**Comment by aschonfeld** [comment] 2020-03-27 01:13
@MichalRIcar thanks so much for all the work you're doing on this!  I think I'm going to spend some time tomorrow researching profiling tooling available to see if I can identify where most of the work is being done on startup.

Now for the the question about memory consumption around successive calls to `dtale.show` .  Each time you call `dtale.show` another dataframe is stored in memory, which is why memory continues to grow.  I've added a rudimentary check to see if a dataframe you're passing to dtale has been passed before and warns the user if that is the case.  Here is the logic behind the check (this is taken from the README):
* Are row & column count the same as a previously loaded piece of data?
* Are the names and order of columns the same as a previously loaded piece of data?

Now, you can ignore this check by passing `ignore_duplicates=True` to `dtale.show` but then you might end up storing a bunch of copies of the same dataframe in memory.

Now there is a way you can clear up memory usage in dtale (at the risk of losing dataframes you're currently viewing) by using the following snippet:
```
import dtale.global_state as global_state

global_state.cleanup()
```
This clears all data in memory associated with dtale.  This might course of action might be a little harsh in which case I suggest using the UI to clear up unused dataframes.  Here's how:
1) go to the main menu in the upper lefthand corner of your grid
2) click "Instances"
3) each row in this grid is for a dataframe you've loaded to D-Tale, if you click the minus button on the far left cell of any row (except for the row of the data you're currently viewing) it will drop that dataframe from memory freeing up space
![image](https://user-images.githubusercontent.com/11547371/77711109-64865180-6fa6-11ea-8a40-bd5b277e60e3.png)

Hope this helps and any suggestions around better ways to make memory management more apparent to the user would be great.  Maybe putting a limit on memory consumption where it will drop dataframes based on the least recent loaded?

**Comment by MichalRIcar** [comment] 2020-04-07 18:44
Hello, happy to say that D-Tale now works fine and came back to 8sec load as before. 

Thank you very much for you amazing support and your time spending on this with me!

Best,

Michal

**Comment by aschonfeld** [comment] 2020-04-07 19:00
@MichalRIcar that's great to hear!  I'll close this out for now but if anything else arises (or need new features) please don't hesitate to ask 👍

**Closed by aschonfeld** 2020-04-07 19:00 UTC
