### ISSUE TITLE
Wrong code snippet in the Build Column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#500] opened 2021-05-26 18:56 UTC
![image](https://user-images.githubusercontent.com/2202483/119715851-75dd1f00-be32-11eb-8a22-b484540ed3d5.png)

/d should be \d

**Comment by reza1615** [comment] 2021-05-27 11:48
The code is not complete
![image](https://user-images.githubusercontent.com/2202483/119820813-df573f00-bebf-11eb-8d71-e40c64122c78.png)

**Comment by reza1615** [comment] 2021-05-27 11:49
Undefined function.
![image](https://user-images.githubusercontent.com/2202483/119821018-16c5eb80-bec0-11eb-970d-942db5a4de4f.png)

**Comment by reza1615** [comment] 2021-05-28 22:48
in the https://github.com/man-group/dtale/commit/a8b918ab6ff120d605066972a2b4e40db1d6f8b8
replace - should be \\- in regex - inside [ ] should be escaped

**Comment by aschonfeld** [comment] 2021-05-29 00:16
The first two have been fixed.  I couldn't reproduce your 3rd issue and does you most recent comment mean that the actual code for "Replace Hyphens w/ Space" needs to change as well?

**Comment by reza1615** [comment] 2021-05-29 02:56
Yes the regex should be changed
just replace - with \\-

**Comment by reza1615** [comment] 2021-05-29 15:46
> The first two have been fixed. I couldn't reproduce your 3rd issue and does you most recent comment mean that the actual code for "Replace Hyphens w/ Space" needs to change as well?

Still it shows the Code as undefined() 
![image](https://user-images.githubusercontent.com/2202483/120076403-626cc680-c073-11eb-8a67-469a9756003a.png)

**Comment by aschonfeld** [comment] 2021-05-29 19:07
How are you able to get to where you don't have a "Case" selected? Thats what is causing this but I can't figure out how to do it on my end so I can fix it.

**Comment by aschonfeld** [comment] 2021-05-29 19:11
Nevermind, I figured it out.  I'll just make it stay hidden until you've actually selected a case, unless you want me to select a specific case by default.

**Comment by aschonfeld** [comment] 2021-06-10 03:44
fixed in v1.49.0

**Closed by aschonfeld** 2021-06-10 03:44 UTC
