### ISSUE TITLE
Periods in column names cause page to go blank

### ISSUE THREAD

**Issue by beautah** [man-group/dtale#63] opened 2020-02-14 16:11 UTC
If a data frame column has a period in the name, as in 'meta.site_id' the rendered page goes blank as soon as you click on that column. No errors logged, just blank screen.

dtale 1.7.3
pandas 0.25.1

``

**Comment by aschonfeld** [comment] 2020-02-14 16:22
@beautah good catch! I've been meaning to fix that.  We saw it when using `pd.read_json` and if you had JSON objects multiple levels deep it concatenates them with periods in the column name.  Thus causing the same issue.

Would you be alright with me simply replacing any periods in column names underscores?

**Comment by beautah** [comment] 2020-02-14 16:38
Ha, that's exactly what I did, that's hilarious. I even started digging in
to figure out where to make a pull request, didn't find it right off the
bat. Yes, its a simple elegant, perhaps brilliant solution. Great project
btw, I'll see if I can help out.

**Comment by aschonfeld** [comment] 2020-02-14 16:57
I'll let you know when the fix is in.  For the time being I think theres a `sep` argument you can set in `pd.json_normalize`

**Comment by jboscolo** [comment] 2020-02-18 11:25
I think I am having the same problem with '#' in the column name. I don't think the problem is limited to periods :)

**Comment by aschonfeld** [comment] 2020-02-18 11:29
@jboscolo, thanks for the heads up!  I’m working on a release which includes the other fix.  I’ll include this as well and dig into what other characters pandas doesnt like.

**Comment by aschonfeld** [comment] 2020-02-18 12:51
So it looks like pandas has actually solved this issue, but it won't be available until the release of 1.1.0 [commit](https://github.com/pandas-dev/pandas/commit/fffb9784559ed9797235a4e79692bc8205371478)|[issue](https://github.com/pandas-dev/pandas/issues/27017)

that being said, I have found a possible work around that will allow me to not remove special characters (https://stackoverflow.com/questions/40045545/pandas-query-string-where-column-name-contains-special-characters)

**Comment by aschonfeld** [comment] 2020-02-20 14:01
Fixed this in v.1.7.5.  I ended up using this [solution](https://stackoverflow.com/a/40083013/12616360) which will only work in Python3 and eventually when pandas does a [new release](https://github.com/pandas-dev/pandas/issues/27017) it will handle this problem for us.  Once that happens I'll make this code be conditional on that version of pandas being used.

**Closed by aschonfeld** 2020-02-20 14:01 UTC
