### ISSUE TITLE
bug in unique value + a suggestion 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#344] opened 2020-12-11 16:54 UTC
when the column content is a mix of numbers and strings the value count just shows the numbers. for example, E6A should be in the unique value section
![image](https://user-images.githubusercontent.com/2202483/101931453-7006c080-3ba7-11eb-9d41-f5c27be15bb7.png)

**Comment by reza1615** [comment] 2020-12-11 17:25
Also is it possible to sort the unique value based on frequency, value? 

![image](https://user-images.githubusercontent.com/2202483/101934610-d42b8380-3bab-11eb-9626-216d35e2a862.png)

Now the unique value Mühlberg (6) should be the last (6) case like the graph

**Comment by aschonfeld** [comment] 2020-12-14 04:29
@reza1615 the first part of this is a duplicate of your previous ask to display the data from the "Word Value Counts" in the "Unique Values" section.  Also, I don't think there is actually a bug if you look at raw values "02169" is the most common.

**Comment by aschonfeld** [comment] 2020-12-25 05:47
Updated in v1.29.1

**Closed by aschonfeld** 2020-12-25 05:47 UTC
