### ISSUE TITLE
bug in "Unique count"

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#182] opened 2020-04-16 20:12 UTC
In the demo for below chart shows this error
![image](https://user-images.githubusercontent.com/2202483/79501991-f9f09080-7ffc-11ea-8181-3cfa3db906b5.png)

**Comment by aschonfeld** [comment] 2020-04-20 11:49
I'm working on a new version now and it seems to be fixed so I'll close this when I release v1.8.10
![image](https://user-images.githubusercontent.com/11547371/79748438-69a39b80-82db-11ea-8eff-2d0d797c59b9.png)

**Comment by aschonfeld** [comment] 2020-04-26 16:38
cannot reproduce v1.8.10
![image](https://user-images.githubusercontent.com/11547371/80313719-d1b22000-87ba-11ea-9d31-c2de018cd09e.png)

**Closed by aschonfeld** 2020-04-26 16:38 UTC
