### ISSUE TITLE
Version 1.8.3

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#154] opened 2020-04-05 14:55 UTC
After version 1.8.3 chart map doesn't work (both chart maps)
I tried to reproduce cases in the #145 and it doesn't show any chart

**Comment by aschonfeld** [comment] 2020-04-05 15:53
Sorry, I know what the issue is.  It works for me locally but wont work in the egg because the topojson files I added are not being included.  I'll update that and have a new version out.

**Comment by aschonfeld** [comment] 2020-04-05 17:04
fixed in v1.8.4

**Closed by aschonfeld** 2020-04-05 17:04 UTC
