### ISSUE TITLE
Replicate dtale Correlations tab live demo example

### ISSUE THREAD

**Issue by mindlessbrain** [man-group/dtale#43] opened 2019-12-26 14:04 UTC
Hi,

I am trying to replicate the [live demo](http://andrewschonfeld.pythonanywhere.com/dtale/main/1), specifically the behaviour of the Correlations tab when you have a time series and display its rolling correlation followed by the scatter plots after clicking on the line plot.

I tested with the following code and got the following output:
```
import pandas as pd
import numpy as np
import dtale

ii = pd.date_range(start='2018-01-01', end='2019-12-01', freq='D')
ii = pd.Index(ii, name='date') 

n = ii.shape[0]
c = 5
data = np.random.random((n, c))

df = pd.DataFrame(data, index=ii)

d = dtale.show(df)
```
![image](https://user-images.githubusercontent.com/17765738/71478389-1eb2c500-27ce-11ea-8dc1-c1e1d522887e.png)
![image](https://user-images.githubusercontent.com/17765738/71478379-0b9ff500-27ce-11ea-8207-4e20278075a6.png)

 I also tried resetting the df index in order to put the date as a column as in the demo but got the same behaviour:
`dtale.show(df.reset_index())`

![image](https://user-images.githubusercontent.com/17765738/71478489-b6181800-27ce-11ea-9d61-5b3dabad1748.png)
![image](https://user-images.githubusercontent.com/17765738/71478493-be705300-27ce-11ea-8fc5-8adf1ab758a8.png)

I installed dtale via pip (`pip install --upgrade dtale`) inside an Anaconda environment on Windows.

Does anyone know if I should preformat the data or turn some flag on?

**Comment by aschonfeld** [comment] 2019-12-26 14:22
So I believe the issue is that you only have one data point per date.  The correlations grid will work because it is simply correlating the data of every combination of numeric columns ( 0 vs. 1, 1 vs. 2, 2 vs. 3, etc...) and there are 700 points to compare.  Whereas, when you try to run the timeseries correlation for a column combination (in your case, 3 vs. 0) each day only has one point to correlate against which I believe will return a nan in pandas.

My solution in this case would be to update the logic behind displaying timeseries correlations by not only checking whether a datetime column exists but whether that column contains more than one value per date.  Which I thought it was doing if you look at (https://github.com/man-group/dtale/blob/master/dtale/views.py#L822) but I'll dig a little deeper.

If you would like to see the scatter plot in your example, simply drop the 'date' column from your dataframe before passing it to `dtale.show`.

My apologies for the issue and appreciate you submitting this :)

**Comment by aschonfeld** [comment] 2019-12-26 14:27
Ok, I just realized that (https://github.com/man-group/dtale/blob/master/dtale/views.py#L822) is only checking if multiple dates exist within a datetime column, but not whether multiple values exist for each date (thus warranting a correlation).

I will update this and hopefully get a new version out to you later today.

**Comment by mindlessbrain** [comment] 2019-12-26 14:40
Okay, thanks, @aschonfeld.
I am looking forward to this :)

**Comment by aschonfeld** [comment] 2019-12-26 14:41
In the meantime, here's a snapshot of what your scatter would look like:

![image](https://user-images.githubusercontent.com/11547371/71479771-ec03cf00-27c3-11ea-8ff1-a6f2f0b2e843.png)

**Comment by mindlessbrain** [comment] 2019-12-26 14:58
@aschonfeld, just for clarification. This graph refers to the correlation of Col14 v.s Col3 on each date, thus we'd more than one sample per day. Right?
![image](https://user-images.githubusercontent.com/17765738/71480130-5a518d00-27d6-11ea-8559-244b1f4e872f.png)

I was thinking this would be a rolling correlation as in this [pandas module](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.Rolling.corr.html)

**Comment by aschonfeld** [comment] 2019-12-26 15:31
This is not using a rolling computation.  It is simply performing a groupby on the date column you've selected (if there are multiple available) and then applying a pearson correlation to the groups: https://github.com/man-group/dtale/blob/master/dtale/views.py#L985

For example: `df.groupby('date')[['Col14','Col3']]..corr(method='pearson')`

If you would like a toggle built on the timeseries chart to allow usage of a rolling computation I can certainly do that

**Comment by aschonfeld** [comment] 2019-12-26 16:03
your original issue should be solved in the new I just posted: https://pypi.org/project/dtale/1.6.4/

**Comment by mindlessbrain** [comment] 2019-12-26 16:17
Thanks for the quick solution, @aschonfeld!

Yes, it would be great to have a feature to perform rolling computations. If it's not asking much, it would be nice to be able to specify the computation method.

Please, let me know if you need help implementting or specifying it.

**Comment by aschonfeld** [comment] 2019-12-26 16:33
@mindlessbrain, I've created a new issue for this feature #45.  We can continue the conversation over there and I'll close this.

**Closed by aschonfeld** 2019-12-26 16:33 UTC
