### ISSUE TITLE
Some Dropdown Menu Problems

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#767] opened 2023-06-18 09:18 UTC
Groupby is a feature I use a lot. I thought that the problem I'm going to talk about was caused by colab, but it wasn't. The problem was due to working in full tab. 

You know, when you open dtale in colab, it opens you in a full tab. The problem is that when you start using the groupby feature in the summarize data section, the Col and Agg drop-down menus stay behind the dialog section, you can see this vaguely as seen in the picture. If you don't pay attention, you'll think it's not working at all. It is most comfortable to work with Dtale on a full tab screen, otherwise it is very difficult to use within the frame.

I'm using Firefox, the problem persists in Trobleshoot mode where all add-ons are disabled.O ther browsers have the same problem.

![dtale](https://github.com/man-group/dtale/assets/40146917/1d7f7c7c-8c39-4ae2-ba0e-ecc78f0e288a)

**Comment by aschonfeld** [comment] 2023-06-19 15:09
@T-a-c-h-y-o-n I actually have a fix for this and am working on getting a new version of D-Tale out to pypi to solve this.  Apologies for the inconvenience

**Comment by T-a-c-h-y-o-n** [comment] 2023-06-19 15:21
Hi, I think the problem will be fixed in the new version. Because there are 3 versions of dtale on sample site and it works without any problems. When will the new version drop to the update channel?  
Thanks for everything.

**Comment by aschonfeld** [comment] 2023-06-19 15:31
I'm hoping by tomorrow morning.  The problem is that I'm currently in London and I dont have my personal computer which I usually use for publishing to pypi.  That being said, I'm working on getting my computer here equipped with the ability to publish

**Comment by T-a-c-h-y-o-n** [comment] 2023-06-19 15:51
It's great that the update is coming soon. Dtale is truly an excellent app. I also use colab because it has more processing capability. I am glad to know that you are among the people who developed it. Thanks again.

**Comment by aschonfeld** [comment] 2023-06-19 17:00
Happy to help! Just published it to pypi and it will be in conda-forge soon. Also, if you havent already, please toss your ⭐ on the repo. Thanks

**Comment by T-a-c-h-y-o-n** [comment] 2023-06-19 18:13
It works great. There were some problems outside of this dropdown menu, and they were also fixed.
i'm grateful. 👏 👍  🙏

**Closed** 2023-06-20 00:05 UTC
