### ISSUE TITLE
column describtion

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#396] opened 2021-01-17 04:12 UTC
In the below Screenshot there are these issues:
* date type doesn't have kuratosis metric
* float column the diff desc show as day diff
![Screenshot_20210116-230607_Chrome](https://user-images.githubusercontent.com/2202483/104830812-4bf66900-5850-11eb-8f82-76d452b222b9.jpg)
![Screenshot_20210116-230531_Chrome](https://user-images.githubusercontent.com/2202483/104830816-4ef15980-5850-11eb-94ca-3474800e9119.jpg)

**Comment by aschonfeld** [comment] 2021-01-17 15:27
I'll look into the first issue. As for the second I can't seem to reproduce it, locally or on the demo site.

**Comment by reza1615** [comment] 2021-01-17 16:22
The second one the lag exists in demo. now I checked it has lag of last column asc data

**Comment by aschonfeld** [comment] 2021-01-17 16:36
Can you send a screen recording? I was not able to reproduce

**Comment by reza1615** [comment] 2021-01-17 17:51
Uploading 20210117_124816.mp4…

**Comment by reza1615** [comment] 2021-01-17 17:54
select a float column > select date column > select float 
You will see it has lag and shows previous types data

**Comment by aschonfeld** [comment] 2021-01-17 21:27
Thanks that really helps, I'll take a look

**Comment by aschonfeld** [comment] 2021-01-25 02:07
Fixed in v1.32.0

**Closed by aschonfeld** 2021-01-25 02:07 UTC
