### ISSUE TITLE
Jupyter Notebook - showing table not working

### ISSUE THREAD

**Issue by jarach** [man-group/dtale#64] opened 2020-02-19 09:38 UTC
Example behavior:
![image](https://user-images.githubusercontent.com/58830859/74818289-a87a9c80-52fe-11ea-8611-5b7459e824a4.png)

When I run 2nd cell with `d.open_browser()`  it opens (as expected) a new browser tab with the table.
After that when I re-run the 1st cell the table appeared as expected in the notebook.

I did it several times and it started being worse. Running command:
'd = dtale.show(df, notebook=True)`
takes long time to display the table (over 2min).

I restarted kernel and tested several combinations of commands. Only following works:
![image](https://user-images.githubusercontent.com/58830859/74819824-440d0c80-5301-11ea-9f6a-e1301ea70130.png)
The last 2 cell take very long time to run.

And after several runs it stopped working at all:
![image](https://user-images.githubusercontent.com/58830859/74820971-2e98e200-5303-11ea-9977-8bf7c6fc735f.png)
![image](https://user-images.githubusercontent.com/58830859/74821020-3fe1ee80-5303-11ea-8a83-50a886965153.png)

I was restarting kernel each time. I even restarted jupyter notebook several times.

Sorry for so many screenshots. I wanted to explain the issue in details.
I hope it helps.

**Comment by aschonfeld** [comment] 2020-02-20 15:44
@jarach Sorry, was working on getting v1.7.5 out.  I will begin looking at this today.  The more screenshots the better! 👍

**Comment by aschonfeld** [comment] 2020-02-21 14:02
@jarach couple questions:

1) we're you calling `dtale.show(df)` everytime you're executing a cell?  If so, D-Tale is not smart enough to know that you're continually passing the same dataframe in so it will open an instance everytime you call it.  So one way around that issue is to store your instance in a variable and then keep viewing that instance
![image](https://user-images.githubusercontent.com/11547371/75040167-2c13c500-5488-11ea-9447-14b36b05eed5.png)
If you need to update the data associated with that instance you can do:
`d.dtata = new_df`
or
`d.data['new_col'] = new_col`

2) Another bug is that when you call `dtale.instances()` it returns a dictionary of all the ids of the data you've "shown" and their instances.  So just executing that in a cell might be costly because it will try to render every instance afterwards.  I might change the functionality of this to only return the ids and then once you see the ids you can pick one and do `dtale.get_instance(id)` to view the data

To get around the issue of showing the same dataframe everytime I could try using something like `pandas.util.testing.assert_frame_equal` to check if that data has already been loaded but I think it might be very costly depending on the size of your data.

I think a better approach would be to have another message display each time you call `dtale.show` that tells you how many instances are open (and maybe how much memory you're consuming, might be too costly)

**Comment by aschonfeld** [comment] 2020-02-21 15:58
Here's a demo of the new duplicate data checking: 
![image](https://user-images.githubusercontent.com/11547371/75049975-1a86e900-5499-11ea-9825-af4c66e5b1ee.png)

**Comment by Robin-Sky** [comment] 2020-02-21 16:34
I seem to be getting the same issue in Google Cloud's AI platform notebooks:     seems to return a blank preview too
![image](https://user-images.githubusercontent.com/28983420/75052555-b7607b00-54c7-11ea-8e34-0dca94722f73.png)

Same in Jupyter classic notebook mode:
![image](https://user-images.githubusercontent.com/28983420/75052690-e676ec80-54c7-11ea-82d4-73bd009289b6.png)

Am wondering whether this is a technical limitation of using a hosted notebook in GCP, or whether Google restricted some actions in their Jupyterlab environment.

**Comment by aschonfeld** [comment] 2020-02-21 17:20
Yes, there is a limitation on using D-Tale in hosted notebooks.  You would have to go to the administrators running those notebook services and ask them if you can allow port 40000 (the first port D-Tale checks when it starts up) to be viewable.

I've already sent requests out to google collab & kaggle to see if they will allow this, but for the time being theres not much that can be done about it.

You may want to try:
```
d = dtale.show(df)
print(d.main_url())
```
and then copying and pasting that link into a new tab.  There is a small chance that the issue is around how the notebook is hosted (https) and how D-Tale is hosted (http).  But most likely the former is true and you'll have to speak with the admins.

As for the issue with the `open_browser` if requires that a default browser be set in whatever environment you try to call it from.  Without it then it can't determine how to start up the browser.  Looks like it looks for the BROWSER environment variable (https://docs.python.org/2/library/webbrowser.html)

**Comment by Robin-Sky** [comment] 2020-02-21 17:33
Thanks for the speedy answer @aschonfeld - makes sense.
Have a good weekend.

**Comment by aschonfeld** [comment] 2020-02-21 20:17
Just released v1.7.6 with the duplicate data check.  I'm going to close this issue since the other aspects are related issues with how notebooks are being hosted rather than with code.

**Closed by aschonfeld** 2020-02-21 20:17 UTC
