### ISSUE TITLE
3D scatter and Surface chart shows error

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#245] opened 2020-08-12 18:45 UTC
3D scatter and Surface charts show dtype error
![image](https://user-images.githubusercontent.com/2202483/90054895-7b55e800-dcaa-11ea-9320-b08b0389b5bc.png)

**Comment by aschonfeld** [comment] 2020-08-14 02:09
@reza1615 Interestingly enough, that same issue does not occur for me.  Those selections don't really make a good looking chart by the way.  🤣 Is there any way you might be able to send me a dump of the data?

**Comment by aschonfeld** [comment] 2020-08-20 02:19
Closing, since it cannot be reproduced

**Closed by aschonfeld** 2020-08-20 02:19 UTC
