### ISSUE TITLE
Timeseries plots with boolean values give empty plots with integer Y Scales

### ISSUE THREAD

**Issue by lcorrigan** [man-group/dtale#553] opened 2021-08-17 13:02 UTC
I might just not be wrangling Dtale correctly, but I've not been able to run a line or scatter plot that has datetime[64] for X and boolean as Y.  The only way I can get a line or dots to appear is if I select an aggregation option but my use-case is more like for watching a network connection thrash over time.  To contrast, I ran the same query in VSCode and plotted directly in Plotly - the outcome there was what I was looking to achieve with Dtale.   I'd appreciate some help if this is just a user-operator issue and can convert the values to something else if that's what Dtale is looking for.  I'm running Dtale 1.54.1 and python 3.8.10.

![Dtale_Plotting_BoolScatter](https://user-images.githubusercontent.com/12451259/129729846-9fdb7ee2-95dd-45f6-9900-b0ceb4eeb807.png)

**Comment by aschonfeld** [comment] 2021-08-17 13:48
Yea, I'm sorry thats another bug.  For some reason the "No Aggregation" option is not displaying what you want. I'll fix that as well.

For the time being, if your x-axis values (timestamps) are unique then setting the aggregation to "Sum" or "Mean" should give you what you want as a work-around.  Apologies

**Comment by lcorrigan** [comment] 2021-08-17 14:01
Thanks @aschonfeld.  The x values are indeed unique but Dtale wasn't happy with your workaround suggestions.  Sum or Mean throw errors.  I'm still just getting to know Dtale so it's not blocking me at all.  Thanks.

Traceback (most recent call last):
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\dash_application\charts.py", line 3248, in build_chart
    scatter_code = scatter_code_builder(data, x, y, axes_builder, **kwargs)
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\dash_application\charts.py", line 847, in scatter_code_builder
    dict_merge(title, build_scatter_layout(axes_builder([y_val])[0], z))
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\dash_application\charts.py", line 348, in _build_axes
    yaxis_cfg = dict(title=update_label_for_freq_and_agg(y), type=scale)
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\dash_application\layout\layout.py", line 661, in update_label_for_freq_and_agg
    return ", ".join([_freq_handler(sub_val) for sub_val in make_list(val)])
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\dash_application\layout\layout.py", line 661, in <listcomp>
    return ", ".join([_freq_handler(sub_val) for sub_val in make_list(val)])
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\dash_application\layout\layout.py", line 644, in _freq_handler
    if sub_val.endswith("|{}".format(agg)):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by aschonfeld** [comment] 2021-08-17 14:08
Ok, I think the issue is that the code is not correctly converting the booleans to numeric data when there is no aggregation specified.  It's converting it to a string because that's what it needs to be when it's used in the x-axis.

As for your most recent exception, are you choosing one of the frequency-based versions of your timestamp column for the y-axis?  Looks like thats the case based on the stacktrace.  Do you mind sharing a snapshot of your chart inputs?  Just trying to narrow down what is going on.  Thanks

**Comment by aschonfeld** [comment] 2021-08-18 12:22
@lcorrigan just released v1.55.0 with a fix for this, let me know if you still have issues

**Closed by aschonfeld** 2021-08-18 12:22 UTC

**Comment by lcorrigan** [comment] 2021-08-18 13:10
Thanks @aschonfeld, when using 1.54, I was not using one of the frequency-based versions of timestamp. Sorry I didn't send a snapshot at the time.  I've tried with 1.55 - it no longer needs an aggregation to plot it (cool), but the scale is kind of messed up. Still treated as integers though a bool (note however dtale recognizes the column is a bool in the data view) and has duplicate entries in the yaxis labels.  If I use mean, the scale makes more sense in a way.
![1 55_using Mean](https://user-images.githubusercontent.com/12451259/129903814-e62643d0-9757-4bed-9f05-4e36427b1c85.png)
![1 55_using UniqueCount](https://user-images.githubusercontent.com/12451259/129903825-b85cc6ed-009d-49eb-8386-60f363b0b40e.png)
![1 55_Reapeating_yscale_ints_for_bools](https://user-images.githubusercontent.com/12451259/129903835-f71aca69-070b-441c-a9c9-4163f89b474f.png)

**Comment by aschonfeld** [comment] 2021-08-22 13:44
So under the hood, when plotly is aggregating booleans it is converting them to integers (0-false, 1-true) so there's not really a way to change the y-axis ticks to say "True"/"False" because there is a good chance that the final aggregated outcomes will not be 1 or 0.

I can try adding some logic which will check the dtype of the column(s) in the y or z-axes and if they are boolean then show ticks representing True(1)/False(0) but it could look a little odd when using aggregations the final value is something like 0.55 (some true, some false) but I think the tooltips on hover will still show you the raw value in that case.

**Comment by lcorrigan** [comment] 2021-08-23 11:45
@aschonfeld , I understand - hard to make it do everything in one. 

I think people can relate **1=True, 0=False** easier than relating a float to a bool. I can understand doing a count of values, but can't predict why someone would want a Mean of boolean.  It's not my UI, but I'd personally deactivate aggregation options that don't make sense for the column data type - but that's easy for me to say, as I'm not the one doing all the work like yourself.  I'm also not sure why plotly displays the axis as boolean on my end. 

I've found that since the resulting plot doesn't let you change things like axis label names etc, I've been just using your fancy export code button and tweaking things back in VSCode when I need to be picky.

Thanks,

**Comment by aschonfeld** [comment] 2021-08-24 01:00
Ok, I think I got it working:
![image](https://user-images.githubusercontent.com/11547371/130538545-5a31a479-1b7f-43bc-8c09-472d85ea8c9c.png)

It will definitely look a little weird when you're using aggregations which produce values outside of 1 & 0 because you won't be able to see the "True"/"False" ticks, so maybe I should turn off the "True"/"False" display for specific aggregations.  If you agree, which ones should I keep it on for?

**Comment by lcorrigan** [comment] 2021-08-24 11:19
@aschonfeld, there aren't any aggregations that would result in True/False, so my humble suggestion would be:

- If Y values selected are boolean columns and no aggregations are selected, display True/False (preference) or 1 / 0. 
- If Y values selected are boolean columns and aggregrations **are** selected, any outcome is going to be of numeric type, so display only numeric.  
- If multiple Y values are selected and not all of them are boolean columns, only display numeric whether aggregations are chosen or not.  Numeric for bool is probably better than trying to make sense of 'True/False' for an array of floats, for example.

As mentioned, I think people are accustomed to using 1 = True, 0 = False, so I think displaying as numeric (int or float) for all cases is still intuitive, so long as the non-aggregated versions of the plots show all the points on the plot. Maybe numeric only would be easier to implement.  Problem with the ints earlier, was that the plot was putting multiple '1's and '0's ticks in the Y column, which didn't make sense.

**Comment by aschonfeld** [comment] 2021-09-01 03:19
updated in v1.56.0
